### ISSUE TITLE
Why using discord.py from github in requirements.txt?

### ISSUE THREAD

**Issue by Nalin-Angrish** [NrdyBhu1/detective-naoto#2]
Why using discord.py from github in requirements.txt when it could simply be `discord`?

**Comment by NrdyBhu1** [comment]
`¯\_(ツ)_/¯`, latest version

**Comment by Nalin-Angrish** [comment]
Really? Even PyPI has the latest version and it is always the stable version.

**Comment by NrdyBhu1** [comment]
`¯\_(ツ)_/¯`

**Comment by Nalin-Angrish** [comment]
Lmao I forgot to close this issue 😅

**Comment by NrdyBhu1** [comment]
lmao
